## OnlyFans Express Messenger
## File: docker-compose.yml
## Purpose: Local Postgres for development
## Created: 2025-08-05 – v1.0

version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_NAME: ofdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      ONLYFANS_API_KEY: ${ONLYFANS_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ofdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

## End of File – Last modified 2025-08-05
